# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GuoanCommunitySDK-Swift-Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GuoanCommunitySDK-Swift-Example
  pod 'GuoanCommunitySDK'

  target 'GuoanCommunitySDK-Swift-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GuoanCommunitySDK-Swift-ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
