# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GuoanCommunitySDK-iOS-Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'GuoanCommunitySDK'

  # Pods for GuoanCommunitySDK-iOS-Example

  target 'GuoanCommunitySDK-iOS-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GuoanCommunitySDK-iOS-ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
